# Generated by Django 3.0.8 on 2020-07-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreoAppl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidores',
            old_name='adminServidores',
            new_name='adminServ',
        ),
    ]
