# Generated by Django 3.0.8 on 2020-07-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreoAppl', '0002_auto_20200712_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidores',
            name='direccionIp',
            field=models.CharField(max_length=25),
        ),
    ]
